Repository Project-AETHA/aetha-frontend, pull requests merged in 2024-08, with the labels that each got.

#77 Add BuyBook Page , Change Cards for tiers , change shop page.
  src/components/Buybook.jsx
  src/components/Buytiers.jsx
  src/components/SearchBar.jsx
  src/components/Subscribe.jsx
  src/components/ViewBooks.jsx
  src/components/routes/General.jsx
  src/pages/BuyBook.jsx
  src/pages/Shop.jsx
Labels: feature, improvement

#79 Admin-finance ui
  src/components/routes/Admin.jsx
  src/pages/Admin/ContentManagement/ApproveNovel.jsx
  src/pages/Admin/ContentManagement/ContentList.jsx
  src/pages/Admin/ContentManagement/ContentManagemenet.jsx
  src/pages/Admin/Dashboard/Dashboard.jsx
  src/pages/Admin/Finance/Advertisements.jsx
  src/pages/Admin/Finance/EBookSelling.jsx
  src/pages/Admin/Finance/Finance.jsx
  src/pages/Admin/Finance/PreSeliing.jsx
Labels: feature, improvement

#80 admin dashboard
  src/components/routes/Admin.jsx
Labels: feature

#81 Writer
  public/images/books/book4.png
  public/images/books/book5.png
  public/images/books/book6.png
  public/images/books/book7.png
  public/images/books/book8.png
  public/images/books/book9.png
  src/components/Writer-dashboard/AuthorDashboard.jsx
  src/components/Writer-dashboard/PoemsPage.jsx
  src/components/routes/Writer.jsx
  src/pages/AddEbook.jsx
  src/pages/AddShortStory.jsx
  src/pages/Advertising.jsx
  src/pages/Chapters.jsx
  src/pages/Ebook.jsx
  src/pages/FirstChapter.jsx
  src/pages/Revenue.jsx
  src/pages/SstSubmitions.jsx
  src/pages/Submitions.jsx
  src/pages/UpgradeToWriter.jsx
  src/pages/test.jsx
Labels: feature, enhancement, improvement, fix

#82 admin-finance Ui
  src/components/routes/Admin.jsx
  src/pages/Admin/Complaints/Complaints.jsx
  src/pages/Admin/ContentManagement/ApproveNovel.jsx
  src/pages/Admin/ContentManagement/ContentList.jsx
  src/pages/Admin/Dashboard/Dashboard.jsx
  src/pages/Admin/Finance/Advertisements.jsx
  src/pages/Admin/Finance/EBookSelling.jsx
  src/pages/Admin/Finance/PreSeliing.jsx
  src/pages/Admin/Finance/Subscriptions.jsx
Labels: feature, enhancement, improvement

#84 Writer UI updates
  src/pages/Chapters.jsx
Labels: improvement

#85 ui changes
  src/pages/Admin/Finance/Finance.jsx
  src/pages/Admin/UserManagement/SingleUser.jsx
  src/pages/Admin/UserManagement/UserManagement.jsx
Labels: enhancement, improvement

#86 feature enhancements
  src/layouts/ProfileDashboardLayout.jsx
  src/pages/Pro_achievements.jsx
  src/pages/Pro_favorites.jsx
  src/pages/Pro_posts.jsx
  src/pages/Pro_reviews.jsx
  src/pages/Profile.jsx
Labels: enhancement
